Get-AppxPackage king.com.CandyCrush* | Remove-AppxPackage
Get-AppxPackage Microsoft.3DBuilder | Remove-AppxPackage
Get-AppxPackage Microsoft.Microsoft3DViewer | Remove-AppxPackage
Get-AppxPackage Microsoft.BingNews | Remove-AppxPackage
Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage
Get-AppxPackage Microsoft.FreshPaint | Remove-AppxPackage
Get-AppxPackage Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage
Get-AppxPackage Microsoft.MixedReality.Portal | Remove-AppxPackage
Get-AppxPackage Microsoft.MSPaint* | Remove-AppxPackage
Get-AppxPackage Microsoft.NetworkSpeedTest | Remove-AppxPackage
Get-AppxPackage Microsoft.People* | Remove-AppxPackage
Get-AppxPackage Microsoft.Print3D* | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsMaps* | Remove-AppxPackage
Get-AppxPackage Microsoft.WindowsFeedbackHub | Remove-AppxPackage
Get-AppxPackage Microsoft.Xbox* | Remove-AppxPackage
Get-AppxPackage Microsoft.YourPhone | Remove-AppxPackage
Get-AppxPackage Microsoft.ZuneMusic* | Remove-AppxPackage
Get-AppxPackage SpotifyAB.SpotifyMusic | Remove-AppxPackage

Get-AppxPackage *.AdobePhotoshopExpress | Remove-AppxPackage
Get-AppxPackage *.Duolingo-LearnLanguagesforFree | Remove-AppxPackage
Get-AppxPackage *.Twitter | Remove-AppxPackage
Get-AppxPackage *messaging* | Remove-AppxPackage
Get-AppxPackage *microsoft.windowscommunicationsapps* | Remove-AppxPackage
Get-AppxPackage Flipboard.Flipboard | Remove-AppxPackage
